### ISSUE TITLE
Feat: Add a form in Contact Us

### ISSUE THREAD

**Issue by wpaddiso999** [wpaddiso999/Corazon-de-oro#11]
User Story:
As a website visitor, I want to be able to easily contact the business by filling out a form on the "Contact Us" page, providing my contact information and the reason for reaching out, so that I can communicate my inquiries or feedback effectively.

Persona:
- Name: Sarah
- Role: Potential Customer
- Background: Sarah is interested in the products/services offered by the business and wants to inquire about pricing and availability before making a purchase.

Business Value:
- Increase customer engagement by providing an easy and convenient way for visitors to reach out.
- Capture valuable customer feedback and inquiries, which can be used for improving products/services and customer experience.
- Generate leads by collecting contact information from potential customers interested in the business offerings.

Feature:
- Implement a contact form on the "Contact Us" page of the website.
- Fields to include:
  - Name
  - Email
  - Phone Number (optional)
  - Message/Reason for reaching out

Tasks:
1. Design the layout and appearance of the contact form on the "Contact Us" page.
2. Develop the frontend components of the form using HTML, CSS, and JavaScript.
3. Implement backend functionality to handle form submissions and store data securely.
4. Validate form inputs to ensure they meet required criteria (e.g., valid email format).
5. Test the form across different devices and browsers to ensure compatibility and responsiveness.
6. Deploy the updated "Contact Us" page with the contact form feature to the live website.

Acceptance Criteria:
1. The contact form is prominently displayed on the "Contact Us" page of the website.
2. Required fields (Name, Email, and Message) are clearly indicated.
3. The form should gracefully handle both successful and unsuccessful form submissions, providing appropriate feedback to the user.
4. Input validation is implemented for the email field to ensure it accepts only valid email addresses.
5. The form submission is securely handled, and user data is stored safely.
6. The contact form is responsive and functions correctly on various screen sizes and devices.
7. Upon successful submission, users receive a confirmation message, and their information is forwarded to the appropriate department for handling inquiries or feedback.

By following this user story, the business can effectively implement a contact form feature that enhances communication with website visitors, thereby improving customer engagement and potentially generating new leads.

**Comment by sjiang1** [comment]
The estimated done time for this PBI is 4/4/2024
